because Have bad repo and can't download
error.GitError: XPerience-AOSP/android_device_motorola_falcon rev-list (u'^69831d4d467c505a54abdc9d1e4f64f173d79e83', 'HEAD', '--'): fatal: bad object 69831d4d467c505a54abdc9d1e4f64f173d79e83